### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by ndsvw** [lukemurraynz/awesome-azure-architecture#27]
Hello, I found some broken links:

- [x] https://fasttrack.azure.com/live/language/en (file: README.md, error: ENOTFOUND)
- [x] https://resources.azure.com/ (file: README.md, status code: 401)
- [x] https://customercocreation.microsoft.com/ (file: README.md, error: ENOTFOUND)
- [x] https://www.azuremonk.com/ (file: README.md, error: ECONNRESET)
- [x] https://dtucalculator.azurewebsites.net/ (file: README.md, error: ENOTFOUND)
- [x] http://microsoftazurewebsitescheatsheet.info/ (file: README.md, error: ENOTFOUND)
- [x] https://azurechecklist.com/ (file: README.md, error: ECONNREFUSED)

**Comment by lukemurraynz** [comment]
> Hello, I found some broken links:
> 
> - [ ] https://fasttrack.azure.com/live/language/en (file: README.md, error: ENOTFOUND)
> - [ ] https://resources.azure.com/ (file: README.md, status code: 401)
> - [ ] https://customercocreation.microsoft.com/ (file: README.md, error: ENOTFOUND)
> - [ ] https://www.azuremonk.com/ (file: README.md, error: ECONNRESET)
> - [ ] https://dtucalculator.azurewebsites.net/ (file: README.md, error: ENOTFOUND)
> - [ ] http://microsoftazurewebsitescheatsheet.info/ (file: README.md, error: ENOTFOUND)
> - [ ] https://azurechecklist.com/ (file: README.md, error: ECONNREFUSED)
> 

Thank you!

**Comment by lukemurraynz** [comment]
Resolved - https://github.com/lukemurraynz/awesome-azure-architecture/commit/0d14dd2296e842a2de7c9c0007a8f4605ee21305
