### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by mikeroyal** [lukemurraynz/awesome-azure-architecture#32]
Hi @lukemurraynz, I love this awesome-azure list you've made  would you mind  if I added to a link to this GitHub repo to the Azure Development section in My [Windows 11 Guide](https://github.com/mikeroyal/Windows-11-Guide)? I would also make sure to credit you by adding link to your GitHub Profile as well.

**Comment by lukemurraynz** [comment]
No problem from me.
